import type {
  CircleEvent,
  Listing,
  Message,
  Offer,
  Person,
  Request,
} from "./types";

/** The current (logged-in) user. */
export const ME: Person = {
  id: "me",
  name: "من",
  avatar: "🧑",
  relation: "friend",
  level: "A",
  deals: 12,
  city: "تهران",
  inMyCircle: true,
  memberSince: "۱۴۰۳",
  responseRate: 95,
  lastActive: "امروز",
  endorsementsReceived: 5,
};

export const PEOPLE: Person[] = [
  // ---- People directly in my circle ----
  {
    id: "sara",
    name: "سارا",
    avatar: "👩",
    relation: "family",
    level: "A",
    note: "خواهرم",
    deals: 9,
    city: "تهران",
    inMyCircle: true,
    memberSince: "۱۴۰۲",
    responseRate: 92,
    lastActive: "دیروز",
    endorsementsReceived: 4,
  },
  {
    id: "reza",
    name: "رضا",
    avatar: "🧔",
    relation: "friend",
    level: "A",
    note: "دوست صمیمی از دوران دانشگاه",
    deals: 14,
    city: "تهران",
    inMyCircle: true,
    memberSince: "۱۴۰۱",
    responseRate: 88,
    lastActive: "۳ ساعت پیش",
    endorsementsReceived: 6,
  },
  {
    id: "mina",
    name: "مینا",
    avatar: "👩‍💼",
    relation: "colleague",
    level: "B",
    note: "همکار در شرکت",
    deals: 6,
    city: "تهران",
    inMyCircle: true,
  },
  {
    id: "ali",
    name: "علی",
    avatar: "👨",
    relation: "neighbor",
    level: "B",
    note: "همسایه‌ی واحد روبه‌رو",
    deals: 5,
    city: "تهران",
    inMyCircle: true,
  },
  {
    id: "nima",
    name: "نیما",
    avatar: "🧑‍🦱",
    relation: "friend",
    level: "C",
    note: "دوستِ باشگاه",
    deals: 3,
    city: "کرج",
    inMyCircle: true,
  },

  // ---- Friends-of-friends (reachable through a trust path) ----
  {
    id: "hossein",
    name: "حسین",
    avatar: "👨‍🏫",
    relation: "acquaintance",
    level: "C",
    note: "همکار سارا",
    deals: 8,
    city: "تهران",
    inMyCircle: false,
  },
  {
    id: "maryam",
    name: "مریم",
    avatar: "👩‍🔧",
    relation: "acquaintance",
    level: "C",
    note: "دوست رضا",
    deals: 11,
    city: "تهران",
    inMyCircle: false,
  },
  {
    id: "kaveh",
    name: "کاوه",
    avatar: "🧑‍🦲",
    relation: "acquaintance",
    level: "C",
    note: "برادر مینا",
    deals: 4,
    city: "تهران",
    inMyCircle: false,
  },
  {
    id: "dariush",
    name: "داریوش",
    avatar: "👴",
    relation: "acquaintance",
    level: "C",
    note: "دوست کاوه",
    deals: 7,
    city: "تهران",
    inMyCircle: false,
  },
  {
    id: "leila",
    name: "لیلا",
    avatar: "👩‍🦰",
    relation: "acquaintance",
    level: "C",
    note: "آشنای نیما",
    deals: 2,
    city: "کرج",
    inMyCircle: false,
  },
];

export const LISTINGS: Listing[] = [
  {
    id: "l1",
    title: "مبل راحتی سه‌نفره، تمیز و سالم",
    description:
      "مبل راحتی سه‌نفره رنگ طوسی، حدود سه سال استفاده شده، کاملاً تمیز و بدون پارگی. به‌خاطر تغییر دکوراسیون می‌فروشم.",
    type: "sale",
    price: 8500000,
    category: "لوازم خانه",
    image:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
    sellerId: "sara",
    postedAt: "۲ ساعت پیش",
    condition: "در حد نو",
    privacy: "ABC",
    endorsements: [{ personId: "reza", type: "verify_item" }],
    trustPath: [],
    city: "تهران",
  },
  {
    id: "l2",
    title: "آموزش پیانو برای کودکان",
    description:
      "آموزش پیانو ویژه‌ی کودکان ۶ تا ۱۲ سال، در منزل خودتان یا آنلاین. هر جلسه ۴۵ دقیقه. صبور و باتجربه.",
    type: "service",
    price: 600000,
    category: "آموزش",
    image: "🎹",
    sellerId: "hossein",
    postedAt: "۵ ساعت پیش",
    privacy: "AB",
    endorsements: [
      { personId: "sara", type: "know_seller" },
      { personId: "sara", type: "verify_quality" },
    ],
    trustPath: [{ personId: "sara", relationLabel: "خواهر من" }],
    city: "تهران",
  },
  {
    id: "l3",
    title: "لباس و اسباب‌بازی کودک — رایگان",
    description:
      "چند دست لباس نوزاد و اسباب‌بازی سالم که دیگر استفاده نمی‌کنیم. به‌صورت رایگان به هرکسی که نیاز دارد می‌دهیم.",
    type: "donation",
    category: "کودک",
    image: "🎁",
    sellerId: "reza",
    postedAt: "دیروز",
    privacy: "ABC",
    endorsements: [],
    trustPath: [],
    city: "تهران",
  },
  {
    id: "l4",
    title: "آیفون ۱۳ کارکرده، ۱۲۸ گیگ",
    description:
      "آیفون ۱۳ آبی، ۱۲۸ گیگابایت، سلامت باتری ۸۹٪. همراه با قاب و گلس. بدون خط و خش جدی.",
    type: "sale",
    price: 28000000,
    category: "موبایل",
    image: "📱",
    sellerId: "mina",
    postedAt: "دیروز",
    condition: "کارکرده",
    privacy: "AB",
    endorsements: [{ personId: "ali", type: "dealt_before" }],
    trustPath: [],
    city: "تهران",
  },
  {
    id: "l5",
    title: "پراید ۹۵، بیمه کامل",
    description:
      "پراید مدل ۹۵، رنگ سفید، بیمه تا آخر سال، لاستیک نو. فنی سالم و آماده‌ی استفاده. تخفیف پای معامله.",
    type: "sale",
    price: 165000000,
    category: "خودرو",
    image: "🚗",
    sellerId: "dariush",
    postedAt: "۲ روز پیش",
    condition: "کارکرده",
    privacy: "referral",
    endorsements: [
      { personId: "mina", type: "verify_item" },
      { personId: "ali", type: "know_seller" },
      { personId: "reza", type: "verify_quality" },
    ],
    trustPath: [
      { personId: "mina", relationLabel: "همکار من" },
      { personId: "kaveh", relationLabel: "برادر مینا" },
    ],
    city: "تهران",
  },
  {
    id: "l6",
    title: "تعمیر لوازم خانگی (یخچال، لباسشویی)",
    description:
      "تعمیر تخصصی یخچال و ماشین لباسشویی در محل. تشخیص رایگان، ضمانت کار. سابقه‌ی ۱۰ ساله.",
    type: "service",
    category: "خدمات فنی",
    image: "🛠️",
    sellerId: "maryam",
    postedAt: "۲ روز پیش",
    privacy: "ABC",
    endorsements: [{ personId: "reza", type: "dealt_before" }],
    trustPath: [{ personId: "reza", relationLabel: "دوست من" }],
    city: "تهران",
  },
  {
    id: "l7",
    title: "معاوضه تردمیل با دوچرخه",
    description:
      "یک دستگاه تردمیل خانگی سالم دارم و دنبال یک دوچرخه‌ی شهری در همان حدود قیمت هستم. آماده‌ی معاوضه.",
    type: "exchange",
    category: "ورزش",
    image: "🚲",
    sellerId: "ali",
    postedAt: "۳ روز پیش",
    condition: "سالم",
    privacy: "AB",
    endorsements: [],
    trustPath: [],
    city: "تهران",
  },
  {
    id: "l8",
    title: "قرض دادن چادر مسافرتی ۴ نفره",
    description:
      "چادر مسافرتی ۴ نفره دارم که برای آخر هفته‌ها قرض می‌دهم. مناسب سفر و طبیعت‌گردی. فقط با هماهنگی قبلی.",
    type: "loan",
    category: "سفر",
    image: "⛺",
    sellerId: "leila",
    postedAt: "۳ روز پیش",
    privacy: "referral",
    endorsements: [],
    trustPath: [{ personId: "nima", relationLabel: "دوست من" }],
    city: "کرج",
  },
  {
    id: "l9",
    title: "مشاوره مالی و سرمایه‌گذاری",
    description:
      "مشاوره‌ی برنامه‌ریزی مالی شخصی و آشنایی با ابزارهای سرمایه‌گذاری. جلسه‌ی اول مشاوره‌ی رایگان.",
    type: "service",
    price: 900000,
    category: "مشاوره",
    image: "💹",
    sellerId: "nima",
    postedAt: "۴ روز پیش",
    privacy: "ABC",
    endorsements: [],
    trustPath: [],
    city: "کرج",
  },
  {
    id: "l10",
    title: "پرستاری کودک (بعدازظهرها)",
    description:
      "نگهداری از کودک در بعدازظهرها، با تجربه و مورد اعتماد. ساعت‌های انعطاف‌پذیر، در محدوده‌ی تهران.",
    type: "service",
    price: 450000,
    category: "خدمات خانگی",
    image: "👶",
    sellerId: "sara",
    postedAt: "۵ روز پیش",
    privacy: "A",
    endorsements: [{ personId: "reza", type: "know_seller" }],
    trustPath: [],
    city: "تهران",
  },
  // ---- Listings restricted enough that I cannot see them (privacy demo) ----
  {
    id: "l11",
    title: "ساعت هوشمند اپل واچ سری ۷",
    description:
      "اپل واچ سری ۷، سالم و کامل با جعبه. فقط برای نزدیک‌ترین افراد حلقه.",
    type: "sale",
    price: 19000000,
    category: "دیجیتال",
    image: "⌚",
    sellerId: "kaveh",
    postedAt: "۶ ساعت پیش",
    condition: "کارکرده",
    privacy: "A",
    endorsements: [],
    trustPath: [{ personId: "mina", relationLabel: "همکار من" }],
    city: "تهران",
  },
  {
    id: "l12",
    title: "طراحی لوگو و هویت بصری",
    description: "طراحی لوگوی حرفه‌ای برای کسب‌وکارها. نمونه‌کار ارسال می‌شود.",
    type: "service",
    price: 2500000,
    category: "طراحی",
    image: "🎨",
    sellerId: "leila",
    postedAt: "۱ روز پیش",
    privacy: "AB",
    endorsements: [],
    trustPath: [{ personId: "nima", relationLabel: "دوست من" }],
    city: "کرج",
  },
];

export const REQUESTS: Request[] = [
  {
    id: "r1",
    title: "صندلی اداری ارگونومیک می‌خوام",
    description:
      "برای دفتر کارم دنبال یک صندلی اداری ارگونومیک سالم هستم. ترجیحاً کارکرده‌ی تمیز.",
    category: "لوازم اداری",
    image: "🪑",
    requesterId: "sara",
    postedAt: "۱ ساعت پیش",
    budget: 3000000,
    privacy: "ABC",
    trustPath: [],
    endorsements: [{ personId: "reza", type: "know_seller" }],
    city: "تهران",
  },
  {
    id: "r2",
    title: "دوچرخه‌ی کوهستان دست‌دوم",
    description:
      "یک دوچرخه‌ی کوهستان سالم سایز ۱۷ یا ۱۸ می‌خوام. اگر کسی می‌فروشه خبر بده.",
    category: "ورزش",
    image: "🚵",
    requesterId: "mina",
    postedAt: "۴ ساعت پیش",
    budget: 12000000,
    privacy: "AB",
    trustPath: [],
    endorsements: [],
    city: "تهران",
  },
  {
    id: "r3",
    title: "معلم خصوصی ریاضی برای کنکور",
    description:
      "دنبال یک معلم خوب و باحوصله برای ریاضی کنکور تجربی هستم. ترجیحاً با معرفی.",
    category: "آموزش",
    image: "📐",
    requesterId: "hossein",
    postedAt: "دیروز",
    privacy: "AB",
    trustPath: [{ personId: "sara", relationLabel: "خواهر من" }],
    endorsements: [
      { personId: "ali", type: "dealt_before" },
      { personId: "reza", type: "know_seller" },
    ],
    city: "تهران",
  },
  {
    id: "r4",
    title: "ماشین لباسشویی سالم — فوری",
    description:
      "ماشین لباسشویی‌ام خراب شده، فوری یک دستگاه سالم دست‌دوم می‌خوام. ممنون می‌شم اگر سراغ دارید.",
    category: "لوازم خانه",
    image: "🌀",
    requesterId: "reza",
    postedAt: "دیروز",
    budget: 8000000,
    privacy: "ABC",
    trustPath: [],
    endorsements: [{ personId: "mina", type: "know_seller" }],
    city: "تهران",
  },
];

export const OFFERS: Offer[] = [
  {
    id: "o1",
    requestId: "r1",
    fromId: "ali",
    message: "یه صندلی اداری ارگونومیک تقریباً نو دارم، سالم و تمیز. اگه بخوای می‌فرستم عکس.",
    price: 2500000,
    postedAt: "۴۰ دقیقه پیش",
  },
  {
    id: "o2",
    requestId: "r2",
    fromId: "nima",
    message: "دوچرخه‌ی کوهستان سایز ۱۷ دارم که کم استفاده شده. فریم سالم.",
    price: 9000000,
    postedAt: "۲ ساعت پیش",
  },
  {
    id: "o3",
    requestId: "r4",
    fromId: "mina",
    message: "یه ماشین لباسشویی اضافه داریم که سالمه. می‌تونم نشونت بدم.",
    postedAt: "۵ ساعت پیش",
  },
];

export const EVENTS: CircleEvent[] = [
  {
    id: "e1",
    title: "کلاس یوگای صبحگاهی",
    description:
      "یوگای ملایم صبحگاهی در فضای باز، مناسب همه‌ی سطح‌ها. زیراندازتان را بیاورید.",
    kind: "class",
    image: "🧘",
    hostId: "mina",
    date: "شنبه ۲۳ خرداد",
    time: "۰۷:۳۰",
    location: "پارک ملت، ورودی شمالی",
    capacity: 12,
    privacy: "ABC",
    attendees: ["sara", "reza", "ali"],
    trustPath: [],
    endorsements: [
      { personId: "sara", type: "know_seller" },
      { personId: "reza", type: "dealt_before" },
    ],
    city: "تهران",
  },
  {
    id: "e2",
    title: "دورهمی خانوادگی آخر هفته",
    description:
      "ناهار خانوادگی و بازی دسته‌جمعی. هر کس یک پیش‌غذا بیاورد. منتظرتانیم!",
    kind: "family",
    image: "🍲",
    hostId: "sara",
    date: "جمعه ۲۲ خرداد",
    time: "۱۳:۰۰",
    location: "خانه‌ی مادربزرگ",
    privacy: "A",
    attendees: ["reza"],
    trustPath: [],
    endorsements: [],
    city: "تهران",
  },
  {
    id: "e3",
    title: "بازارچه‌ی خیریه‌ی محله",
    description:
      "بازارچه‌ی خیریه با دست‌سازه‌ها و خوراکی خانگی؛ درآمد صرف کودکان بی‌سرپرست می‌شود.",
    kind: "charity",
    image: "🎗️",
    hostId: "maryam",
    date: "پنجشنبه ۲۸ خرداد",
    time: "۱۶:۰۰",
    location: "فرهنگسرای محله",
    privacy: "ABC",
    attendees: ["reza", "mina", "nima"],
    trustPath: [{ personId: "reza", relationLabel: "دوست من" }],
    endorsements: [{ personId: "reza", type: "know_seller" }],
    city: "تهران",
  },
  {
    id: "e4",
    title: "playdate کودکان در پارک",
    description:
      "بعدازظهر بازی برای کودکان ۳ تا ۷ سال، با چند بازی گروهی و میان‌وعده‌ی سالم.",
    kind: "kids",
    image: "🧒",
    hostId: "reza",
    date: "یکشنبه ۲۴ خرداد",
    time: "۱۷:۰۰",
    location: "پارک قیطریه",
    capacity: 8,
    privacy: "AB",
    attendees: ["sara"],
    trustPath: [],
    endorsements: [],
    city: "تهران",
  },
  {
    id: "e5",
    title: "سفر گروهی دو روزه به شمال",
    description:
      "سفر دسته‌جمعی به رامسر؛ اقامت ویلایی و برنامه‌ی طبیعت‌گردی. هزینه به‌صورت مشترک.",
    kind: "trip",
    image: "🏞️",
    hostId: "hossein",
    date: "۱ تا ۳ تیر",
    location: "رامسر",
    capacity: 20,
    privacy: "AB",
    attendees: ["sara", "ali", "mina", "nima"],
    trustPath: [{ personId: "sara", relationLabel: "خواهر من" }],
    endorsements: [
      { personId: "sara", type: "know_seller" },
      { personId: "ali", type: "dealt_before" },
    ],
    city: "تهران",
  },
];

let _msgSeq = 0;
function m(
  peerId: string,
  fromMe: boolean,
  text: string,
  postedAt: string,
  read: boolean,
  listingId?: string,
): Message {
  return {
    id: `seed_msg_${_msgSeq++}`,
    peerId,
    fromMe,
    text,
    postedAt,
    read,
    ...(listingId ? { listingId } : {}),
  };
}

// Seed conversations. Ordered so the most-recently-active thread (Sara)
// has the latest indices — threads are derived newest-first from this array.
export const MESSAGES: Message[] = [
  // reza
  m("reza", true, "رضا جان لباس‌های کودک رو می‌خوام برای خواهرزاده‌ام", "۲ روز پیش", true),
  m("reza", false, "حتماً، قابلی نداره 🙂", "۲ روز پیش", true),
  m("reza", false, "لباس‌های کودک رو فردا میارم دمِ در", "۲ روز پیش", true),
  m("reza", false, "راستی این کلاس پیانو رو دیدم، برای دخترت عالیه 👇", "دیروز", false, "l2"),
  // hossein
  m("hossein", true, "سلام آقای حسین، برای کلاس پیانوی دخترم تماس گرفتم", "دیروز", true),
  m("hossein", false, "سلام، خوشحال می‌شم. چند سالشه؟", "دیروز", true),
  m("hossein", true, "۸ سالشه و خیلی علاقه داره", "دیروز", true),
  m("hossein", false, "عالیه. برای کلاس پیانو بعدازظهرها وقت دارم", "دیروز", false),
  // mina
  m("mina", true, "مینا سلام، آیفون ۱۳ت هنوز هست؟", "دیروز", true),
  m("mina", false, "سلام! آره موجوده", "دیروز", true),
  m("mina", false, "آیفون رو برات نگه می‌دارم، نگران نباش", "دیروز", true),
  // sara (most recent, 2 unread)
  m("sara", true, "سلام سارا، مبل راحتی‌ت رو تو سیرکل دیدم", "۱۰:۲۰", true),
  m("sara", false, "سلام عزیزم 🙂 آره هنوز هست", "۱۰:۲۲", true),
  m("sara", true, "کیفیتش که عالیه. می‌تونم بیام ببینمش؟", "۱۰:۲۵", true),
  m("sara", false, "حتماً، آخر هفته خونه‌ام", "۱۰:۳۰", false),
  m("sara", false, "مبل هنوز هست، هر وقت خواستی بیا ببین", "۱۰:۳۲", false),
];
