import type { Listing, Person } from "./types";

/** The current (logged-in) user. */
export const ME: Person = {
  id: "me",
  name: "من",
  avatar: "🧑",
  relation: "friend",
  level: "A",
  deals: 12,
  city: "تهران",
  inMyCircle: true,
};

export const PEOPLE: Person[] = [
  // ---- People directly in my circle ----
  {
    id: "sara",
    name: "سارا",
    avatar: "👩",
    relation: "family",
    level: "A",
    note: "خواهرم",
    deals: 9,
    city: "تهران",
    inMyCircle: true,
  },
  {
    id: "reza",
    name: "رضا",
    avatar: "🧔",
    relation: "friend",
    level: "A",
    note: "دوست صمیمی از دوران دانشگاه",
    deals: 14,
    city: "تهران",
    inMyCircle: true,
  },
  {
    id: "mina",
    name: "مینا",
    avatar: "👩‍💼",
    relation: "colleague",
    level: "B",
    note: "همکار در شرکت",
    deals: 6,
    city: "تهران",
    inMyCircle: true,
  },
  {
    id: "ali",
    name: "علی",
    avatar: "👨",
    relation: "neighbor",
    level: "B",
    note: "همسایه‌ی واحد روبه‌رو",
    deals: 5,
    city: "تهران",
    inMyCircle: true,
  },
  {
    id: "nima",
    name: "نیما",
    avatar: "🧑‍🦱",
    relation: "friend",
    level: "C",
    note: "دوستِ باشگاه",
    deals: 3,
    city: "کرج",
    inMyCircle: true,
  },

  // ---- Friends-of-friends (reachable through a trust path) ----
  {
    id: "hossein",
    name: "حسین",
    avatar: "👨‍🏫",
    relation: "acquaintance",
    level: "C",
    note: "همکار سارا",
    deals: 8,
    city: "تهران",
    inMyCircle: false,
  },
  {
    id: "maryam",
    name: "مریم",
    avatar: "👩‍🔧",
    relation: "acquaintance",
    level: "C",
    note: "دوست رضا",
    deals: 11,
    city: "تهران",
    inMyCircle: false,
  },
  {
    id: "kaveh",
    name: "کاوه",
    avatar: "🧑‍🦲",
    relation: "acquaintance",
    level: "C",
    note: "برادر مینا",
    deals: 4,
    city: "تهران",
    inMyCircle: false,
  },
  {
    id: "dariush",
    name: "داریوش",
    avatar: "👴",
    relation: "acquaintance",
    level: "C",
    note: "دوست کاوه",
    deals: 7,
    city: "تهران",
    inMyCircle: false,
  },
  {
    id: "leila",
    name: "لیلا",
    avatar: "👩‍🦰",
    relation: "acquaintance",
    level: "C",
    note: "آشنای نیما",
    deals: 2,
    city: "کرج",
    inMyCircle: false,
  },
];

export const LISTINGS: Listing[] = [
  {
    id: "l1",
    title: "مبل راحتی سه‌نفره، تمیز و سالم",
    description:
      "مبل راحتی سه‌نفره رنگ طوسی، حدود سه سال استفاده شده، کاملاً تمیز و بدون پارگی. به‌خاطر تغییر دکوراسیون می‌فروشم.",
    type: "sale",
    price: 8500000,
    category: "لوازم خانه",
    image: "🛋️",
    sellerId: "sara",
    postedAt: "۲ ساعت پیش",
    condition: "در حد نو",
    privacy: "ABC",
    endorsements: [{ personId: "reza", type: "verify_item" }],
    trustPath: [],
    city: "تهران",
  },
  {
    id: "l2",
    title: "آموزش پیانو برای کودکان",
    description:
      "آموزش پیانو ویژه‌ی کودکان ۶ تا ۱۲ سال، در منزل خودتان یا آنلاین. هر جلسه ۴۵ دقیقه. صبور و باتجربه.",
    type: "service",
    price: 600000,
    category: "آموزش",
    image: "🎹",
    sellerId: "hossein",
    postedAt: "۵ ساعت پیش",
    privacy: "AB",
    endorsements: [
      { personId: "sara", type: "know_seller" },
      { personId: "sara", type: "verify_quality" },
    ],
    trustPath: [{ personId: "sara", relationLabel: "خواهر من" }],
    city: "تهران",
  },
  {
    id: "l3",
    title: "لباس و اسباب‌بازی کودک — رایگان",
    description:
      "چند دست لباس نوزاد و اسباب‌بازی سالم که دیگر استفاده نمی‌کنیم. به‌صورت رایگان به هرکسی که نیاز دارد می‌دهیم.",
    type: "donation",
    category: "کودک",
    image: "🎁",
    sellerId: "reza",
    postedAt: "دیروز",
    privacy: "ABC",
    endorsements: [],
    trustPath: [],
    city: "تهران",
  },
  {
    id: "l4",
    title: "آیفون ۱۳ کارکرده، ۱۲۸ گیگ",
    description:
      "آیفون ۱۳ آبی، ۱۲۸ گیگابایت، سلامت باتری ۸۹٪. همراه با قاب و گلس. بدون خط و خش جدی.",
    type: "sale",
    price: 28000000,
    category: "موبایل",
    image: "📱",
    sellerId: "mina",
    postedAt: "دیروز",
    condition: "کارکرده",
    privacy: "AB",
    endorsements: [{ personId: "ali", type: "dealt_before" }],
    trustPath: [],
    city: "تهران",
  },
  {
    id: "l5",
    title: "پراید ۹۵، بیمه کامل",
    description:
      "پراید مدل ۹۵، رنگ سفید، بیمه تا آخر سال، لاستیک نو. فنی سالم و آماده‌ی استفاده. تخفیف پای معامله.",
    type: "sale",
    price: 165000000,
    category: "خودرو",
    image: "🚗",
    sellerId: "dariush",
    postedAt: "۲ روز پیش",
    condition: "کارکرده",
    privacy: "referral",
    endorsements: [
      { personId: "mina", type: "verify_item" },
      { personId: "ali", type: "know_seller" },
      { personId: "reza", type: "verify_quality" },
    ],
    trustPath: [
      { personId: "mina", relationLabel: "همکار من" },
      { personId: "kaveh", relationLabel: "برادر مینا" },
    ],
    city: "تهران",
  },
  {
    id: "l6",
    title: "تعمیر لوازم خانگی (یخچال، لباسشویی)",
    description:
      "تعمیر تخصصی یخچال و ماشین لباسشویی در محل. تشخیص رایگان، ضمانت کار. سابقه‌ی ۱۰ ساله.",
    type: "service",
    category: "خدمات فنی",
    image: "🛠️",
    sellerId: "maryam",
    postedAt: "۲ روز پیش",
    privacy: "ABC",
    endorsements: [{ personId: "reza", type: "dealt_before" }],
    trustPath: [{ personId: "reza", relationLabel: "دوست من" }],
    city: "تهران",
  },
  {
    id: "l7",
    title: "معاوضه تردمیل با دوچرخه",
    description:
      "یک دستگاه تردمیل خانگی سالم دارم و دنبال یک دوچرخه‌ی شهری در همان حدود قیمت هستم. آماده‌ی معاوضه.",
    type: "exchange",
    category: "ورزش",
    image: "🚲",
    sellerId: "ali",
    postedAt: "۳ روز پیش",
    condition: "سالم",
    privacy: "AB",
    endorsements: [],
    trustPath: [],
    city: "تهران",
  },
  {
    id: "l8",
    title: "قرض دادن چادر مسافرتی ۴ نفره",
    description:
      "چادر مسافرتی ۴ نفره دارم که برای آخر هفته‌ها قرض می‌دهم. مناسب سفر و طبیعت‌گردی. فقط با هماهنگی قبلی.",
    type: "loan",
    category: "سفر",
    image: "⛺",
    sellerId: "leila",
    postedAt: "۳ روز پیش",
    privacy: "referral",
    endorsements: [],
    trustPath: [{ personId: "nima", relationLabel: "دوست من" }],
    city: "کرج",
  },
  {
    id: "l9",
    title: "مشاوره مالی و سرمایه‌گذاری",
    description:
      "مشاوره‌ی برنامه‌ریزی مالی شخصی و آشنایی با ابزارهای سرمایه‌گذاری. جلسه‌ی اول مشاوره‌ی رایگان.",
    type: "service",
    price: 900000,
    category: "مشاوره",
    image: "💹",
    sellerId: "nima",
    postedAt: "۴ روز پیش",
    privacy: "ABC",
    endorsements: [],
    trustPath: [],
    city: "کرج",
  },
  {
    id: "l10",
    title: "پرستاری کودک (بعدازظهرها)",
    description:
      "نگهداری از کودک در بعدازظهرها، با تجربه و مورد اعتماد. ساعت‌های انعطاف‌پذیر، در محدوده‌ی تهران.",
    type: "service",
    price: 450000,
    category: "خدمات خانگی",
    image: "👶",
    sellerId: "sara",
    postedAt: "۵ روز پیش",
    privacy: "A",
    endorsements: [{ personId: "reza", type: "know_seller" }],
    trustPath: [],
    city: "تهران",
  },
];
